GET http://localhost:3333/tweets

###

GET http://localhost:3333/tweets/212121


###

POST http://localhost:3333/tweets/
Content-Type: application/json

{
  "content": "Hello World",
  "screen_name": "John Doe"
}